[package]
name = "ezemoji"
version = "0.0.1"
authors = ["cowboy8625 <cowboy8625@protonmail.com>"]
edition = "2018"
discription = "Catigoryized Emoji's"
readme = "README.md"
repository = "https://github.com/cowboy8625/ezemoji"
keywords = ["emoji"]
categories = []

[dependencies]
