name: ezemoji Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, macOS-latest]
        rust: [stable, nightly]
        include:
          - rust: stable
            can-fail: false
          - rust: nightly
            can-fail: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Toolchain Information
        run: |
          rustc --version
          rustfmt --version
          rustup --version
          cargo --version

      - name: Check Formatting
        if: matrix.rust == 'stable'
        run: cargo fmt --all -- --check
        continue-on-error: ${{ matrix.can-fail }}

      - name: Clippy Lint
        run: cargo clippy --all-targets-- -D clippy::all
        continue-on-error: ${{ matrix.can-fail }}

      - name: Test default features (std)
        run: cargo test --all-targets
